spring.application.name=funding
spring.data.mongodb.uri=mongodb+srv://bhavyanth02:oygrxbYyv0qktvjf@java-cluster.oud7q.mongodb.net/?retryWrites=true&w=majority&appName=java-cluster
spring.data.mongodb.database=funddb
server.port=8081